version: "3.3"

services:

 mysql-usersdb:
  build:
   context: .
   dockerfile: MySQL.Dockerfile
   labels:
    "mysql-usersdb": "latest"
  image: mysql-usersdb
  ports:
   - "3306:3306"
  deploy:
   replicas: 1
  networks:
   - isolated-network

 users-api:
  build:
   context: .
   dockerfile: UsersAPI.Dockerfile
   labels:
    "users-api": "latest"
  image: users-api
  ports:
   - "5000:5000"
  volumes:
   - "./Database:/Database"
  deploy:
   replicas: 1
  networks: 
   - isolated-network

 orders-api:
  build:
   context: .
   dockerfile: OrdersAPI.Dockerfile
   labels:
    "orders-api": "latest"
  image: orders-api
  ports:
   - "5001:5001"
  deploy:
   replicas: 1
  networks:
   - isolated-network

 order-details-api:
  build:
   context: .
   dockerfile: OrderDetailsAPI.Dockerfile
   labels:
    "order-details-api": "latest"
  image: order-details-api
  ports:
   - "5002:5002"
  deploy:
   replicas: 1
  networks:
   - isolated-network

volumes:
 users-db:
  name: users-db

networks:
 isolated-network:
  driver: bridge