apiVersion: v1
kind: Secret
metadata:
 name: users-api-secret
type: Opaque
data:
 ConnectionStrings__UsersDB: U2VydmVyPW15c3FsLXNlcnZpY2U7RGF0YWJhc2U9bWljcm9zZXJ2aWNlcztVaWQ9YXBwX3VzZXI7UHdkPUFwcEBQYXNzdzByZDs=

---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: users-api-deploy
 labels:
  app: users-api-deploy
 annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
 replicas: 3
 minReadySeconds: 5
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxUnavailable: 0
   maxSurge: 1
 selector:
  matchLabels:
   app: users-api
 template:
  metadata: 
   labels:
    app: users-api
  spec:
   terminationGracePeriodSeconds: 1
   containers:
    - name: users-api-ctr
      image: dkthedon/users-api
      envFrom:
       - secretRef:
          name: users-api-secret 
      ports:
       - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
 name: users-api-service
 labels:
  app: users-api-service
spec:
 type: ClusterIP
 ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
 selector:
  app: users-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: orders-api-deploy
 labels:
  app: orders-api-deploy
 annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
 replicas: 1
 minReadySeconds: 5
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxUnavailable: 0
   maxSurge: 1
 selector:
  matchLabels:
   app: orders-api
 template:
  metadata:
   labels:
    app: orders-api
  spec:
   terminationGracePeriodSeconds: 1
   containers:
    - name: orders-api-ctr
      image: dkthedon/orders-api
      ports:
       - containerPort: 5001

---

apiVersion: v1
kind: Service
metadata:
 name: orders-api-service
 labels:
  app: orders-api-service
spec:
 type: ClusterIP
 ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
 selector:
  app: orders-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: order-details-api-deploy
 labels:
  app: order-details-api-deploy
 annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
 replicas: 3
 minReadySeconds: 5
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxUnavailable: 0
   maxSurge: 1
 selector:
  matchLabels:
   app: order-details-api
 template:
  metadata:
   labels:
    app: order-details-api
  spec:
   terminationGracePeriodSeconds: 1
   containers:
    - name: order-details-api
      image: dkthedon/order-details-api
      ports:
       - containerPort: 5002

---

apiVersion: v1
kind: Service
metadata:
 name: order-details-api-service
 labels:
  app: order-details-api-service
spec:
 type: LoadBalancer
 ports:
  - port: 80
    targetPort: 5002
    nodePort: 32000
    protocol: TCP
 selector:
  app: order-details-api

  